# config.yaml
paths:
  output_dir: "output/simulation_results" # Base directory for outputs
  # Input NIfTI files for tissue segmentation
  wm_nifti: "/Users/c3495249/Coding/Gemini_Pro_Vasculature/data/mida_reoriented_processing_v2/other_reoriented_masks_TARGET_RAS/mida_total_wm_mask_reoriented_RAS.nii.gz"
  gm_nifti: "/Users/c3495249/Coding/Gemini_Pro_Vasculature/data/mida_reoriented_processing_v2/other_reoriented_masks_TARGET_RAS/mida_total_gm_mask_reoriented_RAS.nii.gz"
  csf_nifti: "/Users/c3495249/Coding/Gemini_Pro_Vasculature/data/mida_reoriented_processing_v2/other_reoriented_masks_TARGET_RAS/mida_total_csf_mask_reoriented_RAS.nii.gz" # Optional
  tumor_nifti: "/Users/c3495249/Coding/Gemini_Pro_Vasculature/mida_processed_masks/tumour_mask.nii.gz" # Optional, for angiogenesis simulation
  inspection_dir: "data/inspection" # Directory for saving inspection plots
  # Input arterial centerlines (VTP or TXT)
  # These define roots and terminals of measured vasculature.
  # Synthetic vessels sprout from these terminal points.
  # arterial_centerlines: "/Users/c3495249/Coding/Gemini_Pro_Vasculature/data/mida_reoriented_processing_v2/mida_arteries_mask_centerlines_TARGET_RAS/terminals_world.txt"

simulation:
  simulation_name: "mida_terminals_gbo" # Used for naming output subfolder
  random_seed: 42
  log_level: "INFO" # DEBUG, INFO, WARNING, ERROR
  units:
    length: "mm"
    pressure: "Pa"
    flow_rate: "mm^3/s" # e.g., mm^3/s
    # Ensure constants.py and parameters below match these units
  use_spherical_domain: False  # Set to True to use a sphere, False for NIfTI
  spherical_domain_shape_vox: [200, 200, 200] # Define the overall simulation grid size (voxels)
  spherical_domain_center_vox: [100, 100, 100]   # Center of the sphere in voxel coords
  spherical_domain_radius_vox: 60          # Radius of the sphere in voxels
  spherical_domain_voxel_size_mm: [1, 1, 1] # Physical size of voxels [dx, dy, dz]
tissue_properties:
  # Metabolic rates (blood flow demand per unit volume of tissue, per unit time)
  # Units: e.g., (mm^3_blood / s) / mm^3_tissue = 1/s
  metabolic_rates:
    gm: 0.0167    # Corresponds to ~60 ml/min/100g
    wm: 0.0056    # Corresponds to ~20 ml/min/100g
    csf: 0.0
    tumor_rim: 0.0434 # Higher demand at tumor rim
    tumor_core: 0.003 # Potentially lower in necrotic core
    # If only 'tumor' key exists, it's used for all tumor voxels.
    # If 'tumor_rim' and 'tumor_core' exist, they are used with corresponding segmentations.

  # Tissue permeability for Darcy's Law (e.g., in mm^2 if length is mm)
  permeability:
    gm: 1.0e-7
    wm: 5.0e-8
    tumor: "" # 2.0e-7 # Tumors often have higher permeability

vascular_properties:
  blood_viscosity: 0.0035 # Pa.s (3.5 cP)
  murray_law_exponent: 3
  k_murray_scaling_factor: 0.5
  external_outlet_default_flow: 0.001 # Add missing parameter
  # Initial flow for newly sprouted synthetic terminals before their territory is defined
  initial_terminal_flow: 1.0e-4 # e.g., mm^3/s
  # Minimum and maximum geometric constraints for synthetic vessels
  min_segment_length: 0.1 # mm
  max_segment_length: 2 # mm
  create_intermediate_nodes: true
  intermediate_node_spacing: 0.5
  min_radius: 0.004 # mm (e.g. 5 microns, capillary scale)
  # Relationship: r_i = K_murray * Q_i^(1/murray_law_exponent)
  # K_murray can be derived or set. For now, let's assume it's implicitly handled by radius updates
  # or can be added if explicit scaling is needed.
  # E.g., K_murray = (8 * mu / (PI * pressure_gradient_per_unit_length_optimal))^(-1/4) for Poiseuille flow with optimal shear stress

gbo_growth: # Parameters for the Growth-Based Optimization algorithm
  gbo_growth.enabled: true # Master switch for GBO growth
  max_iterations: 5
  # Cost of metabolic maintenance of vessel wall volume (Power / Volume, e.g. W/m^3 or equivalent)
  # E_metabolic = C_met_vessel_wall * PI * r^2 * L (This should have units of Power)
  # If length in mm, radius in mm, C_met in (mW / mm^3), then E_metabolic in mW.
  # If E_flow (8*mu*L*Q^2 / (PI*r^4)) is in mW, then units are consistent.
  # Viscosity in Pa.s = (N/m^2).s. Length in m. Q in m^3/s. Radius in m.
  # Pa.s * m * (m^3/s)^2 / m^4 = (N/m^2).s * m * m^6/s^2 / m^4 = N.m/s = W (Watts)
  # So if using mm, need to convert: 1 W = 1000 mW. 1 m = 1000 mm.
  # C_met (W/m^3) -> C_met * (1000 mW / (1000mm)^3) = C_met * 1e-6 mW/mm^3
  energy_coefficient_C_met_vessel_wall: 1.0e-1 # mW/mm^3 (example, needs calibration)
  initial_territory_radius: 3.0 

  frontier_search_radius_factor: 3.0 # Multiplies terminal radius
  frontier_search_radius_fixed: 6  # mm (Fixed search distance, must be > initial_territory_radius to find new tissue)
  
  max_move_per_iteration: 3.5  # Maximum mm a terminal can move per iteration
  territory_assignment_inertia: 0.5  # 0-1, higher = more stable territories (0.5 = 50% "stickiness")
  
  max_voxels_for_Rip: 4000             # Max voxels in a new frontier patch (was 30-50)
  max_flow_single_terminal: 0.001  # mm^3/s (Max flow before forcing branch. Was 0.0005)
  # Fraction of total metabolic demand that the GBO aims to satisfy.
  target_perfusion_level: 0.95
  target_domain_perfusion_fraction: 0.95
  # Smooth growth
  direction_memory_factor: 0.3  # How much to blend previous direction (0-1)
  tortuosity_noise_factor: 0.15  # Random perturbation strength (0-0.5)
  # Intermediate nodes for tortuosity
  create_intermediate_nodes: true
  intermediate_node_spacing: 1.5
  
  tissue_constraints:
    avoid_csf: true  # Vessels avoid CSF regions
    tissue_stiffness_effect: false  # Future: growth affected by tissue properties

  pruning:
    enabled: True
    interval: 3  # How often to run pruning (e.g., every 3 GBO iterations)
    min_flow_for_survival: 1.0e-7 # Segments with flow (abs) below this are candidates (mm^3/s)
    min_radius_for_survival: 0.0051 # Segments with radius below this are candidates (mm), slightly > min_radius
    preserve_path_to_active_demand_terminals: True # Try to keep paths to terminals that still have demand
  # Criteria for triggering a bifurcation attempt for a terminal
  branching_trigger_radius_factor: 5 # Branch if current radius > factor * radius_at_last_branch (or initial)
  branching_trigger_territory_voxels: 500 # Branch if territory size (num voxels) exceeds this
  branch_radius_increase_threshold: 1.5 # Branch if radius increases by this factor since last bifurcation
  min_iterations_before_no_growth_stop: 5
  gbo_growth.min_frontier_demand_factor_for_bifurcation: 0.1
  flow_solver_interval: 20     # Run flow solver every 1 GBO iteration. Increase to e.g. 5 or 10 for speed if needed later.

  # Parameters for searching for optimal bifurcation
  bifurcation_candidate_points: 10 # Number of candidate locations for new child terminals
  bifurcation_angle_min_deg: 30.0  # Minimum angle between child branches
  bifurcation_angle_max_deg: 120.0 # Maximum angle between child branches
  bifurcation_length_factor_parent_radius: 10.0 # New segment length as factor of parent radius ( heuristic for new terminal placement)
  bifurcation_max_child_distance: 2.5 # NEW: Max distance (mm) a new child can be from its parent
  # Stop conditions for GBO growth
  stop_criteria:
    # For a branch originating from a measured artery terminal:
    # Stop growing this specific branch if its synthetic segment's radius (connecting to the measured terminal)
    # becomes 'max_radius_factor_measured' times the measured terminal's original radius.
    max_radius_factor_measured: 1.0
    min_flow_improvement: 1.0e-8 # Stop if total perfused flow doesn't improve significantly
    min_radius_for_growth: 0.005 # mm, stop growing branches if they become too small
  
  perfusion_driven_behavior:
    enabled: True # Set to True to enable this new logic
    min_territory_perfusion_ratio: 0.7 # Terminal must meet this % of its demand to seek new frontiers
    # Parameters for sub-branching if poorly perfused (optional, more advanced)
    sub_branching_if_hypoxic: False 
    min_radius_for_hypoxic_sub_branching: 0.05 # mm, if terminal is larger than this, it can try to sub-branch

  seed_points: # Use arterial terminal coordinates as seed points for GBO growth
  - id: outlet_1
    position: [-60.125883, -11.242233, 40.874130]
    initial_radius: 0.499972
  - id: outlet_2
    position: [-60.743472, 18.609706, 35.421612]
    initial_radius: 0.499972
  - id: outlet_3
    position: [-54.227628, 5.751337, 46.633032]
    initial_radius: 0.499972
  - id: outlet_4
    position: [-54.325691, 23.558485, 39.551682]
    initial_radius: 0.499972
  - id: outlet_5
    position: [-46.005830, -29.378987, 47.497986]
    initial_radius: 0.499972


tumor_angiogenesis:
  enabled: true  # Master switch for this entire module

  num_macro_iterations: 3 # Total number of "days" or major cycles of tumor growth + angiogenesis

  # --- Initial Tumor Seeding (if not starting from an already active 'Tumor' mask in tissue_data) ---
  initial_tumor_seed:
    strategy: "auto_center"
    # Ensure these coordinates are within your Tumor_Max_Extent mask
    radius_voxels: 3             # Initial radius of the active tumor seed in voxels

  # --- Tumor Growth (Mesoscale expansion within Tumor_Max_Extent) ---
  tumor_growth:
    steps_per_macro_iter: 1      # How many tumor expansion steps per macro iteration
    expansion_voxels_per_step: 200 # Number of new voxels the active tumor tries to claim per step
    # supply_radius_for_growth_mm: 0.5 # Optional: For more complex "supplied rim" logic (not fully used in current script)

  # --- Tumor Morphology (Rim/Core) ---
  tumor_morphology:
    rim_thickness_voxels: 3      # Thickness of the metabolically active/VEGF-producing rim in voxels

  # --- VEGF Field Settings ---
  vegf_settings:
    production_rate_rim: 1.0     # Relative VEGF production strength in the tumor rim
    # production_rate_core: 0.1  # Optional: VEGF production in the core (can be 0 if necrotic or less active)
    apply_diffusion_blur: true   # Whether to apply Gaussian blur to simulate diffusion
    diffusion_blur_sigma: 2.5    # Sigma for Gaussian blur (in voxel units)

  # --- Vessel Co-option ---
  cooption:
    # When a healthy vessel is engulfed by the active tumor
    radius_dilation_factor_mean: 1.1 # Mean factor by which co-opted vessel radius is multiplied
    radius_dilation_factor_std: 0.05 # Std dev for the dilation factor, adds variability
    permeability_Lp_factor_tumor: 10.0 # Multiplicative factor for hydraulic conductivity (Lp) increase for tumor vessels

  # --- Angiogenic Sprouting ---
  sprouting:
    min_vegf_concentration: 0.2  # Minimum VEGF normalized (0-1 if field is normalized) or absolute concentration to trigger sprouting
    min_parent_vessel_radius_mm: 0.020 # Minimum radius of an existing vessel to be a candidate for sprouting (e.g., 20 microns)
    max_new_sprouts_per_iteration: 5   # Max new sprouts initiated in one angiogenesis *step* (not macro iteration)
    initial_sprout_radius_mm: 0.008    # Radius of a newly formed angiogenic sprout (e.g., 8 microns)
    initial_sprout_length_mm: 0.04     # Initial length of the first segment of a new sprout (e.g., 5x radius)
    # allow_sprout_from_angiogenic: false # Whether new angiogenic vessels can themselves sprout further (can lead to dense networks)

  # --- Angiogenic Vessel Extension ---
  extension:
    step_length_mm: 0.02         # How far an angiogenic tip extends per step along VEGF gradient (e.g., 2-3x its radius)

  # --- Angiogenic Branching (Simplified Stochastic) ---
  angiogenic_branching:
    # Probability of branching for an active tip = branch_probability_factor_vegf * (local_VEGF / max_VEGF)
    branch_probability_factor_vegf: 0.05 # Base factor, e.g., 5% chance if VEGF is max
    branch_angle_spread_deg: 90.0      # Max deviation (e.g., +/- 45 deg) from parent direction for new child branches

  # --- Anastomosis (Tip-to-Segment) ---
  anastomosis:
    search_radius_factor: 3.0    # Search radius for target segment = tip_radius * this_factor
    min_fusion_angle_deg: 100.0  # Tip's last segment vector and vector to target midpoint should form an angle >= this (to avoid fusing back on itself)
    max_dist_to_midpoint_factor: 2.0 # Tip's distance to target segment's midpoint <= tip_radius * this_factor

  # --- Flow Solver and Radius Adaptation during Angiogenesis ---
  flow_solve_interval_macro_iters: 20 # How many macro iterations between running the full 1D flow solver
  min_tumor_terminal_demand: 1.0e-5  # Default Q_flow (mm^3/s) for new angiogenic terminals if more detailed demand isn't calculated

  adaptation: # Rules for how tumor vessel radii change after flow solve
    tumor_radius_factor: 1.0         # Target tumor radius = MurrayRadius * this factor (1.0 = same as healthy, >1 = larger for same flow)
    min_tumor_vessel_radius_mm: 0.006 # Tumor vessels might resist shrinking below this (e.g., 6 microns)

  # --- Saving Intermediate Angiogenesis Results ---
  save_intermediate_interval_macro_iters: 1 # How many macro iterations between saving VTPs and NIfTIs
                                            # Set to 0 or a very large number to disable intermediate saves.
perfusion_solver:
  
  enabled: false # Set to true to run perfusion modeling after vascular growth
  # For 1D network flow solver
  inlet_pressure: 10000 # Pa (approx 75 mmHg) at arterial roots
  # Outlet condition: either fixed pressure at venous terminals or resistance model
  outlet_pressure_venous: 1000 # Pa (approx 15 mmHg)
  # Or, outlet_resistance_venous: value

  # For 3D tissue perfusion (Darcy model)
  # K is in tissue_properties
  darcy_solver_max_iter: 1000
  darcy_solver_tolerance: 1.0e-6

  # For 1D/3D coupling: Q_terminal = coupling_beta * (P_vessel_terminal - P_tissue_at_terminal)
  coupling_beta: 1.0e-7 # mm^3 / (s*Pa) (if units are mm, s, Pa)
  max_iterations_coupling: 50
  convergence_tolerance_coupling: 1.0e-4 # Relative change in flow/pressure
  run_final_1d_flow_solve: false

visualization:
  save_initial_masks: true
  save_intermediate_steps: false # If true, save tree/maps at certain GBO iterations
  intermediate_step_interval: 5 # Save every N iterations
  plot_slice_axis: "axial" # 'axial', 'sagittal', 'coronal' for 2D overlay plots
  plot_slice_index: -1 # Index of slice to plot (-1 for middle slice)
  pyvista_cmap_pressure: "coolwarm"
  pyvista_cmap_radius: "viridis"  # Or "viridis", "coolwarm", etc.
  seed_point_color: "red"    
  seed_marker_radius_scale: 3.0 # Adjust for good visibility of seed markers
  pyvista_background_color: "white"
  domain_mask_color: "lightgrey"     # Or any other color
  domain_mask_opacity: 0.1      # Adjust for visibility
  plot_initial_setup: true             # NEW: Master switch for the initial setup plot
  plot_context_masks_final: true     # Existing: For final plot context
  tumor_seed_marker_color: "magenta" 
  tumor_max_extent_mask_color: "salmon"
  active_tumor_mask_color: "darkred"   # For visualizing the active tumor in final plots
  blender_snapshot_interval: 1
  export_tissue_vtk: true